### ISSUE TITLE
The current release is broken

### ISSUE THREAD

**Issue by cz-Michael** [iamchrismiller/redis-notifier#6]
npm install redis-notifier will fail because it is still using an old version of hiredis even the source code has been updated to the latest version of hiredis, so can you @iamchrismiller make a new release. Thank you.

**Comment by sharathm** [comment]
:+1:

**Comment by iamchrismiller** [comment]
Good to go, Update commit : https://github.com/iamchrismiller/redis-notifier/commit/791ebdcf40995a0086afe394faba96e8dc422192

Release v1.0.0 to NPM.

**Comment by cz-Michael** [comment]
Thank you so much. Now it works for me.
