### ISSUE TITLE
please can you complete the example ? 

### ISSUE THREAD

**Issue by sergiomb2** [iamchrismiller/redis-notifier#8]
TypeError: this._handleExpired is not a function

How and where I should define _handleExpired  ? why you use one underscore ? 
this._handleExpired function could just print "key N was expired" 

btw you may also add this in init of example : 

    var log4js = require('log4js');
    var logger = log4js.getLogger();

**Comment by sergiomb2** [comment]
for example add : 

    eventNotifier._handleExpired = function (emittedKey) {
        console.log("emittedKey " + emittedKey);
    }

**Comment by iamchrismiller** [comment]
Hey Sergio, I updated the README. Those _handle* methods are from my application code at the time. Those are are open to the implementer.

The Logging package is OPTIONAL and can be included if desired.
